---
config:
  layout: dagre
---
flowchart TB

%% ========================================
%% グラフの開始点 (R1, R2)
%% ========================================
n1{"R1"}
n2{"R2"}


%% ========================================
%% R1 ルート (Staffs)
%% ========================================

n1 --> n3{{"Staffsをとる"}}
n3 --> n87("結果分岐")
n87 --> n88["現在の状況"]
n88 --> n22{{"武器を作る"}} & n3

n22 --> n89("結果分岐")
n89 --> n90["現在の状況"]
n90 --> n35{{"MFに侵入する"}} & n93{{"Staffsをとる"}} & n22

n93 --> n94("結果分岐")
n94 --> n97["現在の状況"]
n97 --> n95{{"武器を作る"}} & n99{{"MFに侵入する"}} & n93

n95 --> n96("結果分岐")
n96 --> n98["現在の状況"]
n98 --> n95 & n100{{"MFに侵入する"}} & n101{{"Staffsをとる"}}

n101 --> n102("結果分岐")
n102 --> n105["現在の状況"]
n105 --> n103{{"武器を作る"}} & n106{{"MFに侵入する"}} & n101

n103 --> n104("結果分岐")
n104 --> n107["現在の状況"]
n107 --> n103 & n108{{"MFに侵入する"}} & n109{{"Staffsをとる"}}

n109 --> n110("結果分岐")
n110 --> n113["現在の状況"]
n113 --> n111{{"武器を作る"}} & n114{{"MFに侵入する"}} & n109

n111 --> n112("結果分岐")
n112 --> n115["現在の状況"]
n115 --> n111 & n116{{"MFに侵入する"}}


%% ========================================
%% R2 ルート (Spearheads)
%% ========================================

n2 --> n4{{"Spearheadsをとる"}}
n4 --> n8{{"取りに行くSpearheadsを選択"}}
n8 --> n9("条件分岐")
n9 --> n17{{"取りに行くSpearheadsを選択"}}
n17 --> n28{{"Spearheadsを取る"}}
n28 --> n21(("結果分岐"))
n21 --> n29["現在の状況"]
n29 --> n23{{"武器を作る"}} & n28 & n4

n23 --> n91("結果分岐")
n91 --> n92["現在の状況"]
n92 --> n56{{"Spearheadsをとる"}} & n59{{"Forestに侵入する"}} & n23

n56 --> n61{{"取りに行くSpearheadsを選択"}}
n61 --> n62("条件分岐")
n62 --> n63{{"取りに行くSpearheadsを選択"}}
n63 --> n65{{"Spearheadsをとる"}}
n65 --> n64(("結果分岐"))
n64 --> n66["現在の状況"]
n66 --> n68{{"武器を作る"}} & n70{{"Forestに侵入する"}} & n65 & n56

n68 --> n117("結果分岐")
n117 --> n118["現在の状況"]
n118 --> n68 & n119{{"Forestに侵入する"}} & n120{{"Spearheadsをとる"}}

n120 --> n121{{"取りに行くSpearheadsを選択"}}
n121 --> n122("条件分岐")
n122 --> n123{{"取りに行くSpearheadsを選択"}}
n123 --> n124{{"Spearheadsをとる"}}
n124 --> n125(("結果分岐"))
n125 --> n126["現在の状況"]
n126 --> n127{{"武器を作る"}} & n128{{"Forestに侵入する"}} & n124 & n120

n127 --> n129("結果分岐")
n129 --> n130["現在の状況"]
n130 --> n127 & n131{{"Forestに侵入する"}} & n132{{"Spearheadsをとる"}}

n132 --> n133{{"取りに行くSpearheadsを選択"}}
n133 --> n134("条件分岐")
n134 --> n135{{"取りに行くSpearheadsを選択"}}
n135 --> n136{{"Spearheadsをとる"}}
n136 --> n137(("結果分岐"))
n137 --> n138["現在の状況"]
n138 --> n139{{"武器を作る"}} & n140{{"Forestに侵-入する"}} & n136 & n132

n139 --> n141("結果分岐")
n141 --> n142["現在の状況"]
n142 --> n139